source "https://rubygems.org"

gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jemoji"

# Use specific versions that GitHub Pages supports
gem "jekyll", "~> 3.9.3"
gem "github-pages", "~> 228"
gem "webrick"  # Required for Ruby 3+
